# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
  - job: BuildJob
    steps:
      - script: echo "Building the application..."
        displayName: 'Build Step'

- stage: Test
  dependsOn: Build
  jobs:
  - job: TestJob
    steps:
      - script: echo "Running tests..."
        displayName: 'Test Step'

- stage: Deploy
  dependsOn: Test
  jobs:
  - job: DeployJob
    steps:
      - script: echo "Deploying the application..."
        displayName: 'Deploy Step'
